---

- name: install dependencies
  package:
    name: tar
    state: present

- name: create node_exporter user
  user:
    name: node_exporter
    state: present
    create_home: false

- name: create node_exporter directory
  file:
    path: /etc/node_exporter
    state: directory
    owner: node_exporter
    group: node_exporter
    mode: '0744'

- name: get meta data
  block:
    - name: get latest release data
      uri:
        url: https://api.github.com/repos/prometheus/node_exporter/releases/latest  # yamllint disable-line rule:line-length
        return_content: true
        headers:
          Accept: "application/vnd.github.v3+json"
      register: json_reponse
    - name: get node_exporter version on remote
      slurp:
        src: /etc/node_exporter/node_exporter_version
      register: node_exporter_remote_version
      ignore_errors: true

- name: get checksum
  block:
    - name: get sha256sums-file link
      set_fact:
        _sha256_uri: '{{ item.browser_download_url }}'
      when: "'sha256sums' in item.name"
      with_items: '{{ json_reponse.json.assets }}'
    - name: get checksum from github
      set_fact:
        _checksums: "{{ lookup('url', _sha256_uri, wantlist=True) | list }}"
    - name: get checksum for amd64
      set_fact:
        node_exporter_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ _checksums }}"
      when: "'linux-amd64.tar.gz' in item"
  when: node_exporter_remote_version["failed"] or node_exporter_remote_version["content"] | b64decode != json_reponse.json.tag_name  # yamllint disable-line rule:line-length

- name: download and install node_exporter
  block:
    - name: get node_exporter download link
      set_fact:
        _node_exporter_uri: '{{ item.browser_download_url }}'
      when: "'linux-amd64.tar.gz' in item.name"
      with_items: '{{ json_reponse.json.assets }}'
    - name: download archive
      get_url:
        url: '{{ _node_exporter_uri }}'
        dest: /tmp/node_exporter-linux-amd64.tar.gz
        checksum: 'sha256:{{ node_exporter_checksum }}'
        mode: '0644'
    - name: unpack archive
      unarchive:
        remote_src: true
        src: /tmp/node_exporter-linux-amd64.tar.gz
        dest: /tmp
        list_files: true
      register: _unarchived
    - name: register unarchived folder
      set_fact:
        _unarchived_folder: '{{ _unarchived.files[0].split("/")[0] }}'
    - name: move node_exporter
      copy:
        remote_src: true
        src: '/tmp/{{ _unarchived_folder }}/node_exporter'
        dest: /usr/local/bin/node_exporter
        owner: root
        group: root
        mode: '0755'
    - name: clean up temp
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /tmp/node_exporter-linux-amd64.tar.gz
        - '/tmp/{{ _unarchived_folder }}'
    - name: create binary version file
      template:
        src: node_exporter_version.j2
        dest: /etc/node_exporter/node_exporter_version
        owner: node_exporter
        group: node_exporter
        mode: '0644'
  when: node_exporter_remote_version["failed"] or node_exporter_remote_version["content"] | b64decode != json_reponse.json.tag_name  # yamllint disable-line rule:line-length
  notify: restart node_exporter

- name: copy service file
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/
    mode: '0644'
    owner: root
    group: root
  notify: restart node_exporter

- name: start and enable node_exporter
  service:
    name: node_exporter
    state: started
    enabled: true
